### ISSUE TITLE
Compatibility with imageresizer?

### ISSUE THREAD

**Issue by AndyButland** [episerver/EPiServer.CdnSupport#1]
Hi - thanks for making this available, it looks like a useful helper for caching images at a CDN.  

I've installed it and it's working as expected.  The only problem I'm finding is that I'm not getting my images transformed any more by image resizer.

In other words this URL is transformed correctly to the expected crop size:
`/globalassets/my-image.jpg?preset=hero_desktop`

But this rewritten one isn't:
`/4a109a/globalassets/my-image.jpg?preset=hero_desktop`

Could you advise if that's expected please or if there's a way you've heard of getting these two things to work together?

Many thanks

Andy

**Comment by PeterBridgerZone** [comment]
I have also come across this issue and as such was unable to make use of this solution.

**Comment by bjuris** [comment]
Anyone tried to debug the code?

**Comment by morten-leerhoy** [comment]
in CdnModule.cs 

replace line 53: c.RewritePath("/" + newPath, String.Empty, String.Empty, true);

with: c.RewritePath("/" + newPath, String.Empty, c.Request.QueryString.ToString(), true);

I've not encountered any problems with this modification yet - but haven't tested extensively.

**Comment by jorgenhelgheim** [comment]
@bjuris could you please update the code to reflect @morten-leerhoy comment above. I did not see this thread inbeforehand and had to figure out the same issue as @morten-leerhoy did. I tried to create a pull request, but it seems I have no access.

**Comment by bjuris** [comment]
@jorgenhelgheim You should be able to fork this project and then make a pull request, see https://help.github.com/articles/creating-a-pull-request-from-a-fork/
