### ISSUE TITLE
Image Not found, when it's deleted and uploaded with same name.

### ISSUE THREAD

**Issue by shivapola** [episerver/EPiServer.CdnSupport#8]
I've added the CDN module & CDN media handler to my project. 
When I updated the image with the same name, It's working as expected. If I just refresh the browser new image was showing. 

However, If I delete the Image from Episerver and Upload it with the same name, the Image was not found.  And the path is showing in Recycle-Bin, as shown in the attached image.

![image](https://user-images.githubusercontent.com/49500017/107506447-fcc4ff00-6b95-11eb-801c-a1d12a2884ad.png)

Another Issue:
I've logged out. Still, cache-control was showing as Private. 

Any pointers would be much appreciated. 

Thanks.

**Comment by bjuris** [comment]
Reopen if you still are having problems and think they are related to the CDN module, the module just adds the unique part of the URL and should not be changing the URL.
